#!/bin/bash

python run_deepcrime.py b1.py change_batch_size
python run_deepcrime.py b1.py change_epochs
python run_deepcrime.py b1.py change_learning_rate
python run_deepcrime.py b1.py disable_batching
python run_deepcrime.py b1.py change_activation_function
python run_deepcrime.py b1.py remove_activation_function
python run_deepcrime.py b1.py add_activation_function
python run_deepcrime.py b1.py change_weights_initialisation
python run_deepcrime.py b1.py change_optimisation_function
python run_deepcrime.py b1.py change_gradient_clip
python run_deepcrime.py b1.py change_earlystopping_patience
python run_deepcrime.py b1.py add_bias
python run_deepcrime.py b1.py remove_bias
python run_deepcrime.py b1.py change_loss_function
python run_deepcrime.py b1.py change_dropout_rate
python run_deepcrime.py b1.py add_weights_regularisation
python run_deepcrime.py b1.py change_weights_regularisation
python run_deepcrime.py b1.py remove_weights_regularisation
python run_deepcrime.py b2.py change_batch_size
python run_deepcrime.py b2.py change_epochs
python run_deepcrime.py b2.py change_learning_rate
python run_deepcrime.py b2.py disable_batching
python run_deepcrime.py b2.py change_activation_function
python run_deepcrime.py b2.py remove_activation_function
python run_deepcrime.py b2.py add_activation_function
python run_deepcrime.py b2.py change_weights_initialisation
python run_deepcrime.py b2.py change_optimisation_function
python run_deepcrime.py b2.py change_gradient_clip
python run_deepcrime.py b2.py change_earlystopping_patience
python run_deepcrime.py b2.py add_bias
python run_deepcrime.py b2.py remove_bias
python run_deepcrime.py b2.py change_loss_function
python run_deepcrime.py b2.py change_dropout_rate
python run_deepcrime.py b2.py add_weights_regularisation
python run_deepcrime.py b2.py change_weights_regularisation
python run_deepcrime.py b2.py remove_weights_regularisation
